
CREATE OR REPLACE FUNCTION HANDLE_NEW_AUTH_USER()
RETURNS TRIGGER
LANGUAGE PLPGSQL
SECURITY DEFINER SET SEARCH_PATH = ''
AS $$
BEGIN
  INSERT INTO public.users (id, email)
  VALUES (NEW.id, NEW.email);
  RETURN NEW;
END;
$$;


CREATE OR REPLACE FUNCTION HANDLE_NEW_USER()
RETURNS TRIGGER
LANGUAGE PLPGSQL
SECURITY DEFINER SET SEARCH_PATH = ''
AS $$
BEGIN
  INSERT INTO public.profiles (user_id, first_name, last_name)
  VALUES (NEW.id, '', '');
  RETURN NEW;
END;
$$;

CREATE TRIGGER ON_USER_CREATED
  AFTER INSERT ON public.users
  FOR EACH ROW EXECUTE PROCEDURE HANDLE_NEW_USER();

CREATE TRIGGER ON_AUTH_USER_CREATED
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE HANDLE_NEW_AUTH_USER();

